"""Persistent data for the Student Management System.

This file is updated automatically when records change through the console.
"""

USERS = ({'username': 'admin',
  'password': 'admin123',
  'role': 'administrator',
  'student_id': ''},
 {'username': 'parent', 'password': 'parent123', 'role': 'parent', 'student_id': ''},
 {'username': 'student', 'password': 'student123', 'role': 'student', 'student_id': ''},
 {'username': 'teacher', 'password': 'teacher123', 'role': 'teacher', 'student_id': ''})

STUDENTS = ({'student_id': 'S001',
  'name': 'Chan Mean',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S002',
  'name': 'Sok Dara',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S003',
  'name': 'Keo Rotha',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S004',
  'name': 'Chea Boring',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S005',
  'name': 'Nguon Sovann',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S006',
  'name': 'Lim Heng',
  'department': 'Information Technology Engineering',
  'year': 3},
 {'student_id': 'S007',
  'name': 'Vann Chanthou',
  'department': 'Information Technology Engineering',
  'year': 3},
 {'student_id': 'S008',
  'name': 'Te Tepnorin',
  'department': 'Information Technology Engineering',
  'year': 3},
 {'student_id': 'S009',
  'name': 'San Sreypich',
  'department': 'Information Technology Engineering',
  'year': 1},
 {'student_id': 'S010',
  'name': 'Bun Tharith',
  'department': 'Information Technology Engineering',
  'year': 1},
 {'student_id': 'S011',
  'name': 'Ouk Kalyan',
  'department': 'Information Technology Engineering',
  'year': 4},
 {'student_id': 'S012',
  'name': 'Meas Samnang',
  'department': 'Information Technology Engineering',
  'year': 4},
 {'student_id': 'S013',
  'name': 'Phon Makara',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S014',
  'name': 'Seng Sreyneath',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S015',
  'name': 'Khim Visal',
  'department': 'Information Technology Engineering',
  'year': 2},
 {'student_id': 'S016',
  'name': 'Dara',
  'department': 'Information Technology Engineering',
  'year': 2})

COURSES = ({'code': 'APL101', 'name': 'Application Programing', 'credits': 4},
 {'code': 'CS101', 'name': 'Data Structures', 'credits': 3},
 {'code': 'DB101', 'name': 'Database', 'credits': 3},
 {'code': 'ENG01', 'name': 'English', 'credits': 2},
 {'code': 'MATH101', 'name': 'Discrete Mathematics', 'credits': 3})

ENROLLMENTS = ({'student_id': 'S001', 'course_code': 'APL101'},
 {'student_id': 'S001', 'course_code': 'CS101'},
 {'student_id': 'S001', 'course_code': 'DB101'},
 {'student_id': 'S001', 'course_code': 'MATH101'},
 {'student_id': 'S002', 'course_code': 'APL101'},
 {'student_id': 'S002', 'course_code': 'CS101'},
 {'student_id': 'S002', 'course_code': 'ENG01'},
 {'student_id': 'S002', 'course_code': 'MATH101'},
 {'student_id': 'S003', 'course_code': 'CS101'},
 {'student_id': 'S003', 'course_code': 'DB101'},
 {'student_id': 'S003', 'course_code': 'ENG01'},
 {'student_id': 'S003', 'course_code': 'MATH101'},
 {'student_id': 'S004', 'course_code': 'APL101'},
 {'student_id': 'S004', 'course_code': 'CS101'},
 {'student_id': 'S004', 'course_code': 'DB101'},
 {'student_id': 'S004', 'course_code': 'MATH101'},
 {'student_id': 'S005', 'course_code': 'CS101'},
 {'student_id': 'S005', 'course_code': 'DB101'},
 {'student_id': 'S005', 'course_code': 'ENG01'},
 {'student_id': 'S005', 'course_code': 'MATH101'},
 {'student_id': 'S006', 'course_code': 'APL101'},
 {'student_id': 'S006', 'course_code': 'CS101'},
 {'student_id': 'S006', 'course_code': 'DB101'},
 {'student_id': 'S006', 'course_code': 'ENG01'},
 {'student_id': 'S006', 'course_code': 'MATH101'},
 {'student_id': 'S007', 'course_code': 'APL101'},
 {'student_id': 'S007', 'course_code': 'CS101'},
 {'student_id': 'S007', 'course_code': 'DB101'},
 {'student_id': 'S007', 'course_code': 'ENG01'},
 {'student_id': 'S007', 'course_code': 'MATH101'},
 {'student_id': 'S008', 'course_code': 'APL101'},
 {'student_id': 'S008', 'course_code': 'CS101'},
 {'student_id': 'S008', 'course_code': 'DB101'},
 {'student_id': 'S008', 'course_code': 'ENG01'},
 {'student_id': 'S009', 'course_code': 'CS101'},
 {'student_id': 'S009', 'course_code': 'ENG01'},
 {'student_id': 'S009', 'course_code': 'MATH101'},
 {'student_id': 'S010', 'course_code': 'CS101'},
 {'student_id': 'S010', 'course_code': 'ENG01'},
 {'student_id': 'S010', 'course_code': 'MATH101'},
 {'student_id': 'S011', 'course_code': 'APL101'},
 {'student_id': 'S011', 'course_code': 'CS101'},
 {'student_id': 'S011', 'course_code': 'DB101'},
 {'student_id': 'S011', 'course_code': 'ENG01'},
 {'student_id': 'S011', 'course_code': 'MATH101'},
 {'student_id': 'S012', 'course_code': 'APL101'},
 {'student_id': 'S012', 'course_code': 'CS101'},
 {'student_id': 'S012', 'course_code': 'DB101'},
 {'student_id': 'S012', 'course_code': 'ENG01'},
 {'student_id': 'S012', 'course_code': 'MATH101'},
 {'student_id': 'S013', 'course_code': 'APL101'},
 {'student_id': 'S013', 'course_code': 'CS101'},
 {'student_id': 'S013', 'course_code': 'DB101'},
 {'student_id': 'S013', 'course_code': 'MATH101'},
 {'student_id': 'S014', 'course_code': 'APL101'},
 {'student_id': 'S014', 'course_code': 'CS101'},
 {'student_id': 'S014', 'course_code': 'ENG01'},
 {'student_id': 'S014', 'course_code': 'MATH101'},
 {'student_id': 'S015', 'course_code': 'CS101'},
 {'student_id': 'S015', 'course_code': 'DB101'},
 {'student_id': 'S015', 'course_code': 'ENG01'},
 {'student_id': 'S015', 'course_code': 'MATH101'})

SCORES = ({'student_id': 'S001', 'course_code': 'APL101', 'score': 50.0},
 {'student_id': 'S001', 'course_code': 'CS101', 'score': 88},
 {'student_id': 'S001', 'course_code': 'DB101', 'score': 90},
 {'student_id': 'S001', 'course_code': 'MATH101', 'score': 92},
 {'student_id': 'S002', 'course_code': 'APL101', 'score': 78},
 {'student_id': 'S002', 'course_code': 'CS101', 'score': 76},
 {'student_id': 'S002', 'course_code': 'ENG01', 'score': 88},
 {'student_id': 'S002', 'course_code': 'MATH101', 'score': 82},
 {'student_id': 'S003', 'course_code': 'CS101', 'score': 91},
 {'student_id': 'S003', 'course_code': 'DB101', 'score': 87},
 {'student_id': 'S003', 'course_code': 'ENG01', 'score': 93},
 {'student_id': 'S003', 'course_code': 'MATH101', 'score': 89},
 {'student_id': 'S004', 'course_code': 'APL101', 'score': 84},
 {'student_id': 'S004', 'course_code': 'CS101', 'score': 79},
 {'student_id': 'S004', 'course_code': 'DB101', 'score': 81},
 {'student_id': 'S004', 'course_code': 'MATH101', 'score': 77},
 {'student_id': 'S005', 'course_code': 'CS101', 'score': 94},
 {'student_id': 'S005', 'course_code': 'DB101', 'score': 91},
 {'student_id': 'S005', 'course_code': 'ENG01', 'score': 95},
 {'student_id': 'S005', 'course_code': 'MATH101', 'score': 88},
 {'student_id': 'S006', 'course_code': 'APL101', 'score': 79},
 {'student_id': 'S006', 'course_code': 'CS101', 'score': 83},
 {'student_id': 'S006', 'course_code': 'DB101', 'score': 85},
 {'student_id': 'S006', 'course_code': 'ENG01', 'score': 87},
 {'student_id': 'S006', 'course_code': 'MATH101', 'score': 80},
 {'student_id': 'S007', 'course_code': 'APL101', 'score': 88},
 {'student_id': 'S007', 'course_code': 'CS101', 'score': 90},
 {'student_id': 'S007', 'course_code': 'DB101', 'score': 86},
 {'student_id': 'S007', 'course_code': 'ENG01', 'score': 91},
 {'student_id': 'S007', 'course_code': 'MATH101', 'score': 92},
 {'student_id': 'S008', 'course_code': 'APL101', 'score': 72},
 {'student_id': 'S008', 'course_code': 'CS101', 'score': 75},
 {'student_id': 'S008', 'course_code': 'DB101', 'score': 78},
 {'student_id': 'S008', 'course_code': 'ENG01', 'score': 80},
 {'student_id': 'S009', 'course_code': 'CS101', 'score': 86},
 {'student_id': 'S009', 'course_code': 'ENG01', 'score': 89},
 {'student_id': 'S009', 'course_code': 'MATH101', 'score': 84},
 {'student_id': 'S010', 'course_code': 'CS101', 'score': 78},
 {'student_id': 'S010', 'course_code': 'ENG01', 'score': 82},
 {'student_id': 'S010', 'course_code': 'MATH101', 'score': 76},
 {'student_id': 'S011', 'course_code': 'APL101', 'score': 93},
 {'student_id': 'S011', 'course_code': 'CS101', 'score': 95},
 {'student_id': 'S011', 'course_code': 'DB101', 'score': 94},
 {'student_id': 'S011', 'course_code': 'ENG01', 'score': 97},
 {'student_id': 'S011', 'course_code': 'MATH101', 'score': 96},
 {'student_id': 'S012', 'course_code': 'APL101', 'score': 87},
 {'student_id': 'S012', 'course_code': 'CS101', 'score': 89},
 {'student_id': 'S012', 'course_code': 'DB101', 'score': 85},
 {'student_id': 'S012', 'course_code': 'ENG01', 'score': 92},
 {'student_id': 'S012', 'course_code': 'MATH101', 'score': 90},
 {'student_id': 'S013', 'course_code': 'APL101', 'score': 83},
 {'student_id': 'S013', 'course_code': 'CS101', 'score': 81},
 {'student_id': 'S013', 'course_code': 'DB101', 'score': 79},
 {'student_id': 'S013', 'course_code': 'MATH101', 'score': 82},
 {'student_id': 'S014', 'course_code': 'APL101', 'score': 86},
 {'student_id': 'S014', 'course_code': 'CS101', 'score': 84},
 {'student_id': 'S014', 'course_code': 'ENG01', 'score': 88},
 {'student_id': 'S014', 'course_code': 'MATH101', 'score': 83},
 {'student_id': 'S015', 'course_code': 'CS101', 'score': 77},
 {'student_id': 'S015', 'course_code': 'DB101', 'score': 75},
 {'student_id': 'S015', 'course_code': 'ENG01', 'score': 81},
 {'student_id': 'S015', 'course_code': 'MATH101', 'score': 79})
